---
locale: pt
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Estrutura do loop "while" não é a mais adequada para o problema
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Existe um problema nos sinais de igualdade do loop while
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Existe um problema de sintaxe no código
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: A condição de unidades no estoque esta errada
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Todas as anteriores
  checked: false
name: 'Python: Debug'
